Repository AY2223S1-CS2103-F14-4/tp, pull requests merged in 2022-11, with the labels that each got.

#206 Add PPP draft.
  docs/team/sprintaway.md
Labels: type.Chore

#208 Update PPP
  docs/team/tykcodes.md
Labels: type.Chore

#210 Add PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/kynapy.md
  docs/team/parth-io.md
  docs/team/sprintaway.md
  src/main/java/bookface/commons/util/StringUtil.java
Labels: type.Chore

#211 Add draft PPP for edward
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/edfernape.md
Labels: type.Chore

#212 Fix documentation bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/bookface/MainApp.java
Labels: type.Bug

#213 Resolve bugs
  docs/index.md
  docs/team/parth-io.md
  src/main/java/bookface/commons/util/StringUtil.java
  src/main/java/bookface/logic/commands/add/AddBookCommand.java
  src/main/java/bookface/logic/commands/delete/DeleteUserCommand.java
  src/main/java/bookface/logic/parser/find/FindBookArgumentsParser.java
  src/main/java/bookface/logic/parser/find/FindUserArgumentsParser.java
  src/main/java/bookface/model/ObjectContainsKeywordsPredicate.java
  src/main/java/bookface/ui/HelpWindow.java
Labels: priority.High

#205 Add tests related to loans and return.
  docs/UserGuide.md
  src/main/java/bookface/commons/core/Messages.java
  src/main/java/bookface/logic/commands/LoanCommand.java
  src/main/java/bookface/logic/commands/ReturnCommand.java
  src/main/java/bookface/logic/parser/LoanCommandParser.java
  src/test/java/bookface/logic/commands/CommandTestUtil.java
  src/test/java/bookface/logic/commands/LoanCommandTest.java
  src/test/java/bookface/logic/commands/ReturnCommandTest.java
  src/test/java/bookface/logic/commands/delete/DeleteUserCommandTest.java
  src/test/java/bookface/logic/parser/LoanCommandParserTest.java
  src/test/java/bookface/logic/parser/ReturnCommandParserTest.java
  src/test/java/bookface/testutil/BookBuilder.java
  src/test/java/bookface/testutil/TypicalBooks.java
  src/test/java/bookface/testutil/TypicalDates.java
  src/test/java/bookface/testutil/TypicalPersons.java
Labels: priority.Medium

#214 Fix bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/bookface/commons/core/Messages.java
  src/main/java/bookface/commons/util/LambdaUtil.java
  src/main/java/bookface/logic/parser/ArgumentTokenizer.java
  src/main/java/bookface/logic/parser/CliSyntax.java
  src/main/java/bookface/logic/parser/add/AddSubcommand.java
  src/main/java/bookface/model/book/Book.java
  src/main/java/bookface/model/book/Title.java
  src/main/java/bookface/model/person/Phone.java
  src/main/java/bookface/model/tag/Tag.java
  src/main/java/bookface/storage/JsonSerializableBookFace.java
  src/main/java/bookface/ui/BookCard.java
  src/test/java/bookface/logic/parser/ArgumentTokenizerTest.java
  src/test/java/bookface/logic/parser/add/AddUserArgumentsParserTest.java
  src/test/java/bookface/logic/parser/edit/EditUserArgumentsParserTest.java
Labels: priority.Medium

#216 Fix readme
  README.md
  src/main/java/bookface/logic/commands/LoanCommand.java
  src/main/java/bookface/logic/parser/LoanCommandParser.java
Labels: type.Chore

#219 Add acknowledgements
  docs/DeveloperGuide.md
Labels: type.Chore

#217 Light theme fix and UG fixes
  docs/UserGuide.md
  docs/index.md
  src/main/java/bookface/model/book/Author.java
  src/main/resources/view/LightTheme.css
Labels: type.Enhancement

#220 Edit activity diagrams.
  docs/DeveloperGuide.md
  docs/diagrams/LoanActivityDiagram.puml
  docs/diagrams/ReturnActivityDiagram.puml
  docs/images/LoanActivityDiagram.png
  docs/images/ReturnActivityDiagram.png
Labels: type.Chore

#223 Add instructions for manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Chore

#222 Add final edits to DG + PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/team/edfernape.md
Labels: priority.High

#226 remove unused code
  src/main/java/bookface/logic/commands/ThemeCommand.java
  src/main/java/bookface/model/person/Person.java
  src/main/java/bookface/storage/JsonAdaptedTitle.java
  src/test/java/bookface/logic/commands/CommandTestUtil.java
  src/test/java/bookface/logic/commands/LoanCommandTest.java
  src/test/java/bookface/logic/commands/ReturnCommandTest.java
  src/test/java/bookface/logic/commands/delete/DeleteUserCommandTest.java
  src/test/java/bookface/testutil/BookBuilder.java
  src/test/java/bookface/testutil/BookFaceBuilder.java
  src/test/java/bookface/testutil/TestUtil.java
  src/test/java/bookface/testutil/TypicalBooks.java
  src/test/java/bookface/testutil/TypicalIndexes.java
  src/test/java/bookface/testutil/TypicalPersons.java
Labels: type.Chore

#225 Improve dg
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/Testing.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  src/main/java/bookface/model/BookFace.java
  src/main/java/bookface/model/ReadOnlyBookFace.java
  src/test/java/bookface/logic/commands/CommandTestUtil.java
  src/test/java/bookface/logic/commands/edit/EditUserCommandTest.java
Labels: type.Chore

#227 Fix corrupted file check
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/bookface/commons/util/Date.java
  src/main/java/bookface/commons/util/StringUtil.java
  src/main/java/bookface/model/BookFace.java
  src/main/java/bookface/model/book/Book.java
  src/main/java/bookface/model/person/Person.java
  src/main/java/bookface/model/person/UniquePersonList.java
  src/main/java/bookface/model/util/SampleDataUtil.java
  src/main/java/bookface/storage/JsonAdaptedBook.java
  src/main/java/bookface/storage/JsonAdaptedPerson.java
  src/main/java/bookface/storage/JsonAdaptedTag.java
  src/main/java/bookface/storage/JsonSerializableBookFace.java
  src/test/data/JsonSerializableBookFaceTest/duplicateBookBookFace.json
  src/test/data/JsonSerializableBookFaceTest/duplicatePersonBookFace.json
  src/test/data/JsonSerializableBookFaceTest/invalidBookBookFace.json
  src/test/data/JsonSerializableBookFaceTest/invalidPersonBookFace.json
  src/test/data/JsonSerializableBookFaceTest/typicalBooksBookFace.json
  src/test/data/JsonSerializableBookFaceTest/typicalPersonsBookFace.json
  src/test/java/bookface/storage/JsonAdaptedPersonTest.java
  src/test/java/bookface/testutil/PersonBuilder.java
  src/test/java/bookface/testutil/TypicalDates.java
  src/test/java/bookface/testutil/TypicalPersons.java
Labels: type.Bug

#234 Add tests
  src/main/java/bookface/model/book/Title.java
  src/main/java/bookface/storage/JsonAdaptedBook.java
  src/test/java/bookface/storage/JsonAdaptedBookTest.java
  src/test/java/bookface/testutil/BookBuilder.java
  src/test/java/bookface/testutil/TypicalBooks.java
  src/test/java/bookface/testutil/TypicalDates.java
  src/test/java/bookface/testutil/TypicalPersons.java
Labels: type.Chore

#246 Cite code that is re-used.
  src/main/resources/view/LightTheme.css
Labels: type.Chore
