Repository AY2223S1-CS2103-F14-4/tp, pull requests merged in 2022-10, with the labels that each got.

#103 Add preliminary BookList class.
  src/main/java/bookface/logic/commands/add/AddBookCommand.java
  src/main/java/bookface/logic/parser/CliSyntax.java
  src/main/java/bookface/model/AddressBook.java
  src/main/java/bookface/model/Model.java
  src/main/java/bookface/model/ModelManager.java
  src/main/java/bookface/model/book/Book.java
  src/main/java/bookface/model/book/BookList.java
  src/test/java/bookface/logic/commands/add/AddUserCommandTest.java
Labels: priority.High

#107 Refactor addressbook directly to bookface.
  docs/diagrams/ArchitectureSequenceDiagram.puml
  src/main/java/bookface/MainApp.java
  src/main/java/bookface/logic/Logic.java
  src/main/java/bookface/logic/LogicManager.java
  src/main/java/bookface/logic/commands/ClearCommand.java
  src/main/java/bookface/model/BookFace.java
  src/main/java/bookface/model/Model.java
  src/main/java/bookface/model/ModelManager.java
  src/main/java/bookface/model/ReadOnlyBookFace.java
  src/main/java/bookface/model/book/Book.java
  src/main/java/bookface/model/util/SampleDataUtil.java
  src/main/java/bookface/storage/AddressBookStorage.java
  src/main/java/bookface/storage/JsonAddressBookStorage.java
  src/main/java/bookface/storage/JsonSerializableAddressBook.java
  src/main/java/bookface/storage/Storage.java
  src/main/java/bookface/storage/StorageManager.java
  src/test/java/bookface/logic/LogicManagerTest.java
  src/test/java/bookface/logic/commands/ClearCommandTest.java
  src/test/java/bookface/logic/commands/CommandTestUtil.java
  src/test/java/bookface/logic/commands/EditCommandTest.java
  src/test/java/bookface/logic/commands/FindCommandTest.java
  src/test/java/bookface/logic/commands/add/AddCommandIntegrationTest.java
  src/test/java/bookface/logic/commands/add/AddUserCommandTest.java
  src/test/java/bookface/logic/commands/delete/DeleteUserCommandTest.java
  src/test/java/bookface/logic/commands/list/ListUsersCommandTest.java
  src/test/java/bookface/model/BookFaceTest.java
  src/test/java/bookface/model/ModelManagerTest.java
  src/test/java/bookface/storage/JsonBookFaceStorageTest.java
  src/test/java/bookface/storage/JsonSerializableBookFaceTest.java
  src/test/java/bookface/storage/StorageManagerTest.java
  src/test/java/bookface/testutil/AddressBookBuilder.java
  src/test/java/bookface/testutil/TypicalPersons.java
Labels: priority.Low

#108 Branch add book command
  src/main/java/bookface/logic/commands/add/AddBookCommand.java
  src/main/java/bookface/logic/parser/add/AddBookArgumentsParser.java
  src/main/java/bookface/logic/parser/add/AddSubcommand.java
  src/test/java/bookface/model/BookFaceTest.java
Labels: priority.High

#116 Add List command for Books
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/bookface/logic/commands/list/ListBooksCommand.java
  src/main/java/bookface/logic/parser/list/ListSubcommand.java
  src/main/java/bookface/model/book/BookList.java
  src/main/java/bookface/model/book/TitleContainsKeywordsPredicate.java
  src/test/java/bookface/logic/LogicManagerTest.java
  src/test/java/bookface/logic/commands/CommandTestUtil.java
  src/test/java/bookface/logic/commands/list/ListBooksCommandTest.java
  src/test/java/bookface/logic/parser/PrimaryParserTest.java
  src/test/java/bookface/logic/parser/list/ListCommandParserTest.java
  src/test/java/bookface/testutil/TypicalIndexes.java
Labels: priority.High

#117 Add function to delete books
  .gitignore
  src/main/java/bookface/commons/core/Messages.java
  src/main/java/bookface/logic/commands/delete/DeleteBookCommand.java
  src/main/java/bookface/logic/parser/delete/DeleteBookArgumentsParser.java
  src/main/java/bookface/logic/parser/delete/DeleteSubcommand.java
  src/main/java/bookface/model/BookFace.java
  src/main/java/bookface/model/Model.java
  src/main/java/bookface/model/ModelManager.java
  src/main/java/bookface/model/book/BookList.java
  src/test/java/bookface/logic/commands/add/AddUserCommandTest.java
Labels: priority.High

#118 Add the Find command for books.
  src/main/java/bookface/commons/core/Messages.java
  src/main/java/bookface/commons/util/StringUtil.java
  src/main/java/bookface/logic/commands/FindCommand.java
  src/main/java/bookface/logic/commands/find/FindBookCommand.java
  src/main/java/bookface/logic/commands/find/FindCommand.java
  src/main/java/bookface/logic/commands/find/FindUserCommand.java
  src/main/java/bookface/logic/parser/FindCommandParser.java
  src/main/java/bookface/logic/parser/delete/DeleteUserArgumentsParser.java
  src/main/java/bookface/logic/parser/find/FindBookArgumentsParser.java
  src/main/java/bookface/logic/parser/find/FindCommandParser.java
  src/main/java/bookface/logic/parser/find/FindSubcommand.java
  src/main/java/bookface/logic/parser/find/FindUserArgumentsParser.java
  src/main/java/bookface/logic/parser/list/ListCommandParser.java
  src/main/java/bookface/logic/parser/primary/PrimaryCommands.java
  src/main/java/bookface/model/ObjectContainsKeywordsPredicate.java
  src/main/java/bookface/model/book/TitleContainsKeywordsPredicate.java
  src/main/java/bookface/model/person/NameContainsKeywordsPredicate.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/bookface/commons/util/StringUtilTest.java
  src/test/java/bookface/logic/commands/CommandTestUtil.java
  src/test/java/bookface/logic/commands/FindCommandTest.java
  src/test/java/bookface/logic/commands/find/FindUserCommandTest.java
  src/test/java/bookface/logic/parser/PrimaryParserTest.java
  src/test/java/bookface/logic/parser/find/FindUserArgumentsParserTest.java
  src/test/java/bookface/model/ModelManagerTest.java
  src/test/java/bookface/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/bookface/model/person/ObjectContainsKeywordsPredicateTest.java
  src/test/java/bookface/testutil/TestUtil.java
  src/test/java/bookface/testutil/TypicalBooks.java
Labels: type.Enhancement, priority.Medium

#115 Add UI changes to reflect loans on user and book list.
  docs/UserGuide.md
  src/main/java/bookface/logic/commands/EditCommand.java
  src/main/java/bookface/logic/commands/LoanCommand.java
  src/main/java/bookface/logic/parser/add/AddBookArgumentsParser.java
  src/main/java/bookface/logic/parser/add/AddUserArgumentsParser.java
  src/main/java/bookface/model/BookFace.java
  src/main/java/bookface/model/ModelManager.java
  src/main/java/bookface/model/book/Book.java
  src/main/java/bookface/model/book/BookList.java
  src/main/java/bookface/model/person/Person.java
  src/main/java/bookface/model/person/UniquePersonList.java
  src/main/java/bookface/model/util/SampleDataUtil.java
  src/main/java/bookface/storage/JsonAdaptedBook.java
  src/main/java/bookface/storage/JsonAdaptedPerson.java
  src/main/java/bookface/storage/JsonAdaptedTitle.java
  src/main/java/bookface/ui/BookCard.java
  src/main/java/bookface/ui/BookListPanel.java
  src/main/java/bookface/ui/PersonCard.java
  src/main/resources/view/BookListCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/bookface/storage/JsonAdaptedPersonTest.java
  src/test/java/bookface/testutil/BookBuilder.java
  src/test/java/bookface/testutil/PersonBuilder.java
Labels: priority.Medium

#123 Fixing of loan issues
  src/main/java/bookface/model/BookFace.java
  src/main/java/bookface/model/book/BookList.java
  src/main/java/bookface/model/person/Person.java
  src/main/java/bookface/model/person/UniquePersonList.java
Labels: priority.High

#129 Update ModelClassDiagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LoanActivityDiagram.puml
  docs/diagrams/LoanSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ReturnActivityDiagram.puml
  docs/diagrams/ReturnSequenceDiagram.puml
  docs/images/LoanActivityDiagram.png
  docs/images/LoanSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ReturnActivityDiagram.png
  docs/images/ReturnSequenceDiagram.png
Labels: priority.High

#139 Update Developer Guide to include list implementation
  docs/DeveloperGuide.md
  docs/diagrams/ListActivityDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/ListActivityDiagram.png
  docs/images/ListSequenceDiagram.png
Labels: priority.High

#141 Update build.gradle to enable assertions
  build.gradle
Labels: priority.High

#142 Add preliminary details to DG for adding a book/user.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddBookSimpleDiagram.puml
  docs/images/AddBookSimpleDiagram.png
  src/test/java/bookface/model/BookFaceTest.java
Labels: priority.Medium

#137 Fix resizing issue as stated by Yi Kuang during v1.2 demo
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low

#150 Fix of UI of book title under booklist not wrapping given long book title name.
  src/main/resources/view/BookListCard.fxml
Labels: type.Bug, priority.Low

#154 Add edit command
  src/main/java/bookface/logic/commands/edit/EditBookCommand.java
  src/main/java/bookface/logic/commands/edit/EditCommand.java
  src/main/java/bookface/logic/commands/edit/EditUserCommand.java
  src/main/java/bookface/logic/parser/ArgumentsParsable.java
  src/main/java/bookface/logic/parser/CommandParser.java
  src/main/java/bookface/logic/parser/LoanCommandParser.java
  src/main/java/bookface/logic/parser/Parseable.java
  src/main/java/bookface/logic/parser/ParserUtil.java
  src/main/java/bookface/logic/parser/ReturnCommandParser.java
  src/main/java/bookface/logic/parser/add/AddBookArgumentsParser.java
  src/main/java/bookface/logic/parser/add/AddUserArgumentsParser.java
  src/main/java/bookface/logic/parser/delete/DeleteBookArgumentsParser.java
  src/main/java/bookface/logic/parser/delete/DeleteUserArgumentsParser.java
  src/main/java/bookface/logic/parser/edit/EditBookArgumentsParser.java
  src/main/java/bookface/logic/parser/edit/EditCommandParser.java
  src/main/java/bookface/logic/parser/edit/EditSubcommand.java
  src/main/java/bookface/logic/parser/edit/EditUserArgumentsParser.java
  src/main/java/bookface/logic/parser/find/FindBookArgumentsParser.java
  src/main/java/bookface/logic/parser/find/FindUserArgumentsParser.java
  src/main/java/bookface/logic/parser/list/ListCommandParser.java
  src/main/java/bookface/logic/parser/primary/PrimaryCommand.java
  src/main/java/bookface/model/BookFace.java
  src/main/java/bookface/model/Model.java
  src/main/java/bookface/model/ModelManager.java
  src/main/java/bookface/model/book/Book.java
  src/main/java/bookface/model/book/BookList.java
  src/main/java/bookface/model/person/UniquePersonList.java
  src/test/java/bookface/logic/commands/CommandTestUtil.java
  src/test/java/bookface/logic/commands/add/AddUserCommandTest.java
  src/test/java/bookface/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/bookface/logic/commands/edit/EditUserCommandTest.java
  src/test/java/bookface/logic/parser/CommandParserTestUtil.java
  src/test/java/bookface/logic/parser/PrimaryParserTest.java
  src/test/java/bookface/logic/parser/edit/EditUserArgumentsParserTest.java
  src/test/java/bookface/testutil/EditPersonDescriptorBuilder.java
  src/test/java/bookface/testutil/PersonUtil.java
  src/test/java/bookface/testutil/TypicalBooks.java
  src/test/java/bookface/testutil/TypicalPersons.java
Labels: priority.Medium

#159 Fix Delete classes with respect to Loan case scenarios
  src/main/java/bookface/commons/core/Messages.java
  src/main/java/bookface/logic/commands/delete/DeleteBookCommand.java
  src/main/java/bookface/logic/commands/delete/DeleteUserCommand.java
  src/main/java/bookface/model/book/BookList.java
  src/main/java/bookface/model/book/exceptions/BookOnLoanException.java
  src/main/java/bookface/model/person/UniquePersonList.java
  src/main/java/bookface/model/person/exceptions/PersonLoansExistException.java
Labels: priority.Medium

#160 Enhance display of books loaned by a person
  src/main/java/bookface/model/book/Book.java
  src/main/java/bookface/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement

#163 Add function to list all users and books, and list all users with loans and books on loan
  .gitignore
  docs/DeveloperGuide.md
  src/main/java/bookface/logic/commands/list/ListAllCommand.java
  src/main/java/bookface/logic/commands/list/ListCommand.java
  src/main/java/bookface/logic/commands/list/ListLoansCommand.java
  src/main/java/bookface/logic/parser/list/ListSubcommand.java
  src/main/java/bookface/model/Model.java
Labels: priority.Medium

#161 Add support for invalid date formats.
  docs/UserGuide.md
  src/main/java/bookface/commons/core/Messages.java
  src/main/java/bookface/logic/commands/LoanCommand.java
  src/main/java/bookface/logic/parser/LoanCommandParser.java
  src/main/java/bookface/model/book/Book.java
Labels: priority.Medium

#165 Fix bugs in commands
  src/main/java/bookface/commons/util/Date.java
  src/main/java/bookface/logic/commands/LoanCommand.java
  src/main/java/bookface/logic/commands/edit/EditUserCommand.java
  src/main/java/bookface/logic/commands/list/ListAllCommand.java
  src/main/java/bookface/logic/commands/list/ListBooksCommand.java
  src/main/java/bookface/logic/commands/list/ListCommand.java
  src/main/java/bookface/logic/commands/list/ListLoansCommand.java
  src/main/java/bookface/logic/commands/list/ListOverdueCommand.java
  src/main/java/bookface/logic/commands/list/ListUsersCommand.java
  src/main/java/bookface/logic/parser/edit/EditBookArgumentsParser.java
  src/main/java/bookface/logic/parser/list/ListSubcommand.java
  src/main/java/bookface/model/BookFace.java
  src/main/java/bookface/model/Model.java
  src/main/java/bookface/model/book/Book.java
  src/main/java/bookface/model/book/BookList.java
  src/main/java/bookface/model/book/exceptions/BookOnLoanException.java
  src/main/java/bookface/model/person/Person.java
  src/main/java/bookface/model/person/UniquePersonList.java
  src/main/java/bookface/model/person/exceptions/PersonLoansExistException.java
  src/main/java/bookface/storage/JsonAdaptedBook.java
  src/main/java/bookface/storage/JsonSerializableBookFace.java
Labels: priority.Medium

#164 Add function to list all overdue books and the users who loaned them
  src/main/java/bookface/logic/commands/list/ListCommand.java
  src/main/java/bookface/logic/commands/list/ListOverdueCommand.java
  src/main/java/bookface/logic/parser/list/ListSubcommand.java
  src/main/java/bookface/model/Model.java
  src/main/java/bookface/model/book/Book.java
Labels: priority.Medium

#166 Add edit to ug
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/bookface/logic/commands/edit/EditBookCommand.java
Labels: priority.Medium

#167 Add ability to change the theme of BookFace.
  docs/UserGuide.md
  src/main/java/bookface/logic/commands/ThemeCommand.java
  src/main/java/bookface/ui/MainWindow.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Medium
